export const API_URL = process.env.NODE_ENV === 'production' ? process.env.NEXT_PUBLIC_API_URL : 'http://localhost';
export const SERVER_URL = process.env.NODE_ENV === 'production' ? process.env.NEXT_PUBLIC_SERVER_URL : 'http://localhost:3000';
export const DB_CODE = {
  LOST_CONNECTION: -4,
  UNCAUGHT_ERROR: -3,
  FATAL_ERROR: -2,
  SERVER_ERROR: -1,
  OK: 0,
  CHECK_REQUEST: 1,
  NO_PERMISSION: 2,
  TOKEN_EXPIRED: 3,
  FILE_EMPTY: 4,
  LANGUAGE_NOT_SUPPORTED: 5,
  FAILED_PASSWORD_VALIDATION: 6,
  INVALID_TOKEN: 100,
  EMAIL_ALREADY_OCCUPIED: 101,
  USERNAME_ALREADY_OCCUPIED: 102,
  NO_SUCH_USER: 103,
  PASSWORD_WRONG: 104,
  ALREADY_VERIFIED: 105,
  NO_SUCH_EXHIBITION: 201,
  NO_SUCH_ARTIST: 301,
  NOT_ARTIST: 302,
  NO_SUCH_ARTWORK: 401,
  NOT_OWNER: 403,
  NO_SUCH_SUBSCRIPTION: 501,
  USER_NOT_ADMIN: 901,
};

const DEFINES = {
  API_URL,
  SERVER_URL,
  DB_CODE,
};

export default DEFINES;
